config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => 'admin', as: 'rails_admin'
  devise_for :users #, controllers: { registrations: "registrations" }
  root to: 'pages#home'

  resources :programs do
    member do
      put 'like', to: 'programs#like', as: 'like'
      put 'unlike', to: 'programs#unlike', as: 'unlike'
    end
    resources :applications
  end

  get '/search' => 'search#index'

  get 'about', to: 'pages#about', as: 'about'
  get 'help', to: 'pages#help', as: 'help'
  get 'contact', to: 'pages#contact', as: 'contact'
  get 'business_dashboard',
      to: 'pages#business_dashboard',
      as: 'business_dashboard'
  get 'user_dashboard', to: 'pages#user_dashboard', as: 'user_dashboard'
  get 'team', to: 'pages#team', as: 'team'
  get 'blog', to: 'pages#blog', as: 'blog'
  get 'career', to: 'pages#career', as: 'career_options'
  get 'businesses', to: 'pages#businesses', as: 'businesses'

  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  
end

app/views/pages/about.html.erb
About page placeholder

app/views/pages/business_dashboard.html.erb
<div class="d-flex align-items-start">
  <div class="nav flex-column nav-pills me-3 bg-dark col-lg-1" id="v-pills-tab" role="tablist" aria-orientation="vertical">
    <button class="nav-link active" id="v-pills-home-tab" data-bs-toggle="pill" data-bs-target="#v-pills-home" type="button" role="tab" aria-controls="v-pills-home" aria-selected="true">Home</button>
    <button class="nav-link" id="v-pills-profile-tab" data-bs-toggle="pill" data-bs-target="#v-pills-profile" type="button" role="tab" aria-controls="v-pills-profile" aria-selected="false">Programs</button>
    <button class="nav-link" id="v-pills-messages-tab" data-bs-toggle="pill" data-bs-target="#v-pills-messages" type="button" role="tab" aria-controls="v-pills-messages" aria-selected="false">Applicants</button>
    <button class="nav-link" id="v-pills-settings-tab" data-bs-toggle="pill" data-bs-target="#v-pills-settings" type="button" role="tab" aria-controls="v-pills-settings" aria-selected="false">Edit info</button>
    <button class="nav-link" id="v-pills-experiment-tab" data-bs-toggle="pill" data-bs-target="#v-pills-experiment" type="button" role="tab" aria-controls="v-pills-experiment" aria-selected="false">Add new program</button>
  </div>
  <div class="tab-content" id="v-pills-tabContent">
    <div class="tab-pane fade show active" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab">
      <div class="container">
        <div class="row ">
          <div class="col card ">
            <h3>Welcome back <%= current_user.first_name %></h3>
            <p>You currently have <%= @programs.size %> programs registered</p>
            <p>Your programs currently have <%= @testingarray.sum %> applicants</p>
            <p>Your programs have so far gotten do the math later views</p>
          </div>
        </div>
      </div>
    </div>
    <div class="tab-pane fade" id="v-pills-profile" role="tabpanel" aria-labelledby="v-pills-profile-tab">
      <div class="container">
        <div class="row">
          <div class="col">
            <table class="table table-striped table-bordered table-hover caption-top">
              <caption>The programs that you've created and their current status</caption>
              <thead>
                <tr>
                  <th>Program</th>
                  <th>Headline</th>
                  <th>Due date</th>
                  <th>Status</th>
                  <th>Created on</th>
                  <th>Applications</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                <% @programs.each do |program| %>
                  <tr>
                    <td><%= program.title %></td>
                    <td><%= program.headline %></td>
                    <td> <%= program.application_due_date %> </td>
                    <td><%= program.status %></td>
                    <td><%= program.created_at.strftime("%m/%d/%y at %l:%M %p") %></td>
                    <td><%= link_to "See #{program.applications.size} applications", program_applications_path(program.id), data: { turbo: :true }, method: :get %></td>
                    <td><%= link_to "See", program_path(program.id), data: { turbo: :true }, method: :get, class: 'badge bg-primary' %>
                      <%= link_to "Edit", edit_program_path(program.id), data: {turbo: :true }, method: :get, class: "badge bg-success" %>
                      <%= link_to "Delete", program_path(program.id), data: { turbo: :true, confirm: "Are you sure?" }, method: :delete, class: 'badge bg-danger', remote: true %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
    <div class="tab-pane fade" id="v-pills-messages" role="tabpanel" aria-labelledby="v-pills-messages-tab">
      <div class=container">
        <div class="row">
          <div class="col">
            <h3>Ugh, figure this shit out later.</h3>
            <% @programs.each do |program| %>
              <div class="list-group w-50">
                <label class="list-group-item">
                  <input type="radio" class="form-check-input me-1" name="gender"> <%= program.title %>
                </label>
              </div>
            <% end %>
            <table class="table table-striped table-bordered table-hover caption-top">
              <caption>The applications to your program</caption>
              <thead>
                <tr>
                  <th>User photo</th>
                  <th>Program</th>
                  <th>Applicant Name</th>
                  <th>Submitted on</th>
                  <th>Status</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                <% @applications.each do |application| %>
                  <tr>
                    <td><%= cl_image_tag application.user.photo.key, height: 150, width: 200, crop: :fill, :alt=>"Applicant user photo" %></td>
                    <td><%= application.program.title %></td>
                    <td><%= application.user.first_name %> <%= application.user.last_name %></td>
                    <td><%= application.created_at.strftime("%m/%d/%y at %l:%M %p") %></td>
                    <td><%= application.status %></td>
                    <td><%= link_to "See & Respond", program_application_path(application.program_id, application.id), data: { turbo: :true }, method: :get, class: 'badge bg-primary' %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
    <div class="tab-pane fade" id="v-pills-settings" role="tabpanel" aria-labelledby="v-pills-settings-tab">
      <div class=container">
        <div class="row">
          <div class="col card">
            <h3>Would you like to edit your user profile?  Click here: </h3>
            <%= link_to "Edit your user profile", edit_user_registration_path %>
            <h4>This is your current information</h4>
            <p>Name: <%= current_user.first_name %> <%= current_user.last_name %></p>
            <p>Organization: <%= current_user.organization_name %> </p>
            <p>Email: <%= current_user.email %> </p>
            <p>Location: <%= current_user.location %></p>
          </div>
        </div>
      </div>
    </div>
    <div class="tab-pane fade" id="v-pills-experiment" role="tabpanel" aria-labelledby="v-pills-experiment-tab">
      <div class=container">
        <div class="row">
          <div class="col card">
            <h3>Would you like to add a new program?  Click here: </h3>
            <%= link_to "Add a new program", new_program_path %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/career.html.erb
<h1>Pages#career`</h1>
<p>Find me in app/views/pages/career.html.erb</p>

app/views/pages/home.html.erb
<header class="masthead" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://www.artranked.com/images/ba/ba36d9da66b4df7ba69a49c846c0383d.jpeg);">
  <div class="container position-relative" >
    <div class="row justify-content-center">
      <div class="col-xl-6">
        <div class="text-center text-white">
          <!-- Page heading-->
          <h1 class="mb-5">Some career copy header line catchy bullshit</h1>
          <!-- Signup form-->
          <!-- * * * * * * * * * * * * * * *-->
          <!-- * * SB Forms Contact Form * *-->
          <!-- * * * * * * * * * * * * * * *-->
          <!-- This form is pre-integrated with SB Forms.-->
          <!-- To make this form functional, sign up at-->
          <!-- https://startbootstrap.com/solution/contact-forms-->
          <!-- to get an API token!-->
          <form class="form-subscribe" id="contactForm" data-sb-form-api-token="API_TOKEN">
            <!-- Email address input-->
            <div class="row">
              <div class="col">
                <input class="form-control form-control-lg" id="emailAddress" type="email" placeholder="Email Address" data-sb-validations="required,email" />
                <div class="invalid-feedback text-white" data-sb-feedback="emailAddress:required">Email Address is required.</div>
                <div class="invalid-feedback text-white" data-sb-feedback="emailAddress:email">Email Address Email is not valid.</div>
              </div>
              <div class="col-auto"><button class="btn btn-primary btn-lg disabled" id="submitButton" type="submit">Submit</button></div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</header>
<!-- Icons Grid-->
<section class="features-icons bg-light text-center">
  <div class="container">
    <div class="row">
      <div class="col-lg-4">
        <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
          <div class="features-icons-icon d-flex"><i class="icon-screen-desktop m-auto text-primary"><%= icon('fas', 'question') %></i></div>
          <h3>Fully Responsive</h3>
          <p class="lead mb-0">This theme will look great on any device, no matter the size!</p>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
          <div class="features-icons-icon d-flex"><i class="icon-layers m-auto text-primary"><%= icon('fas', 'share-alt') %></i></div>
          <h3>Bootstrap 5 Ready</h3>
          <p class="lead mb-0">Featuring the latest build of the new Bootstrap 5 framework!</p>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="features-icons-item mx-auto mb-0 mb-lg-3">
          <div class="features-icons-icon d-flex"><i class="icon-check m-auto text-primary"><%= icon('fas', 'dollar-sign') %></i></div>
          <h3>Easy to Use</h3>
          <p class="lead mb-0">Ready to use with your own content, or customize the source files!</p>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Image Showcases-->
<section class="showcase">
  <div class="container-fluid p-0">
    <div class="row g-0">
      <%= image_tag 'https://images.pexels.com/photos/979927/pexels-photo-979927.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500', class: 'col-lg-6 order-lg-2 text-white showcase-img', alt: '' %>
      <div class="col-lg-6 order-lg-1 my-auto showcase-text">
        <h2>Fully Responsive Design</h2>
        <p class="lead mb-0">When you use a theme created by Start Bootstrap, you know that the theme will look great on any device, whether it's a phone, tablet, or desktop the page will behave responsively!</p>
      </div>
    </div>
    <div class="row g-0">
      <%= image_tag 'https://images.pexels.com/photos/1072824/pexels-photo-1072824.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500', class: 'col-lg-6 text-white showcase-img', alt: '' %>
      <div class="col-lg-6 my-auto showcase-text">
        <h2>Updated For Bootstrap 5</h2>
        <p class="lead mb-0">Newly improved, and full of great utility classes, Bootstrap 5 is leading the way in mobile responsive web development! All of the themes on Start Bootstrap are now using Bootstrap 5!</p>
      </div>
    </div>
    <div class="row g-0">
      <%= image_tag 'https://images.pexels.com/photos/167964/pexels-photo-167964.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500', class: 'col-lg-6 order-lg-2 text-white showcase-img', alt: '' %>
      <div class="col-lg-6 order-lg-1 my-auto showcase-text">
        <h2>Easy to Use & Customize</h2>
        <p class="lead mb-0">Landing Page is just HTML and CSS with a splash of SCSS for users who demand some deeper customization options. Out of the box, just add your content and images, and your new landing page will be ready to go!</p>
      </div>
    </div>
  </div>
</section>
<!-- Testimonials I-->
<section class="testimonials text-center bg-light">
  <div class="container">
    <h2 class="mb-5">Why should you post your jobs here...?</h2>
    <div class="row">
      <div class="col-lg-4">
        <div class="testimonial-item mx-auto mb-5 mb-lg-0">
          <%= image_tag 'https://images.pexels.com/photos/39624/padlock-lock-chain-key-39624.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', class: 'img-fluid rounded-circle mb-3', alt: '' %>
          <h5>Creaze can help you unlock your potential!</h5>
          <p class="font-weight-light mb-0">"By doing the hard work of providing you with the tools that you need to make a living, you can expand your capabilities and focus on accomplishing more!"</p>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="testimonial-item mx-auto mb-5 mb-lg-0">
          <%= image_tag 'https://images.pexels.com/photos/6945/sunset-summer-golden-hour-paul-filitchkin.jpg?auto=compress&cs=tinysrgb&dpr=1&w=500', class: 'img-fluid rounded-circle mb-3', alt: '' %>
          <h5>Creaze can help you make a living!</h5>
          <p class="font-weight-light mb-0">"There are many different ways available for you to generate a sustainable income through Creaze.  Let us help you make a living through your creativity."</p>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="testimonial-item mx-auto mb-5 mb-lg-0">
          <%= image_tag 'https://images.pexels.com/photos/2014775/pexels-photo-2014775.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500', class: 'img-fluid rounded-circle mb-3', alt: '' %>
          <h5>Interact with current fans while obtaining new ones!</h5>
          <p class="font-weight-light mb-0">"Connect better with your existing fans and more easily make new ones!"</p>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Testimonials II perhaps?-->
<section class="testimonials text-center bg-light">
  <div class="container">
    <h2 class="mb-5">Are you a student...?</h2>
    <div class="row">
      <div class="col-lg-4">
        <div class="testimonial-item mx-auto mb-5 mb-lg-0">
          <%= image_tag 'https://images.pexels.com/photos/39624/padlock-lock-chain-key-39624.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', class: 'img-fluid rounded-circle mb-3', alt: '' %>
          <h5>Creaze can help you unlock your potential!</h5>
          <p class="font-weight-light mb-0">"By doing the hard work of providing you with the tools that you need to make a living, you can expand your capabilities and focus on accomplishing more!"</p>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="testimonial-item mx-auto mb-5 mb-lg-0">
          <%= image_tag 'https://images.pexels.com/photos/6945/sunset-summer-golden-hour-paul-filitchkin.jpg?auto=compress&cs=tinysrgb&dpr=1&w=500', class: 'img-fluid rounded-circle mb-3', alt: '' %>
          <h5>Creaze can help you make a living!</h5>
          <p class="font-weight-light mb-0">"There are many different ways available for you to generate a sustainable income through Creaze.  Let us help you make a living through your creativity."</p>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="testimonial-item mx-auto mb-5 mb-lg-0">
          <%= image_tag 'https://images.pexels.com/photos/2014775/pexels-photo-2014775.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500', class: 'img-fluid rounded-circle mb-3', alt: '' %>
          <h5>Interact with current fans while obtaining new ones!</h5>
          <p class="font-weight-light mb-0">"Connect better with your existing fans and more easily make new ones!"</p>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Call to Action-->
<section class="call-to-action text-white text-center" id="signup">
  <div class="container position-relative">
    <div class="row justify-content-center">
      <div class="col-xl-6">
        <h2 class="mb-4">Ready to get started? Sign up now!</h2>
        <!-- Signup form-->
        <form class="form-subscribe" id="contactFormFooter" data-sb-form-api-token="API_TOKEN">
          <!-- Email address input-->
          <div class="row">
            <div class="col">
              <input class="form-control form-control-lg" id="emailAddressBelow" type="email" placeholder="Email Address" data-sb-validations="required,email" />
              <div class="invalid-feedback text-white" data-sb-feedback="emailAddressBelow:required">Email Address is required.</div>
              <div class="invalid-feedback text-white" data-sb-feedback="emailAddressBelow:email">Email Address Email is not valid.</div>
            </div>
            <div class="col-auto"><button class="btn btn-primary btn-lg disabled" id="submitButton" type="submit">Submit</button></div>
          </div>
          
          
        </form>
      </div>
    </div>
  </div>
</section>

app/views/pages/user_dashboard.html.erb
<%# tabs %>
<div class="d-flex align-items-start">
  <div class="nav flex-column nav-pills me-3 bg-dark col-lg-1 vh-100" id="v-pills-tab" role="tablist" aria-orientation="vertical">
    <button class="nav-link active" id="v-pills-home-tab" data-bs-toggle="pill" data-bs-target="#v-pills-home" type="button" role="tab" aria-controls="v-pills-home" aria-selected="true">Home</button>
    <button class="nav-link" id="v-pills-profile-tab" data-bs-toggle="pill" data-bs-target="#v-pills-profile" type="button" role="tab" aria-controls="v-pills-profile" aria-selected="false">Saved programs</button>
    <button class="nav-link" id="v-pills-messages-tab" data-bs-toggle="pill" data-bs-target="#v-pills-messages" type="button" role="tab" aria-controls="v-pills-messages" aria-selected="false">Edit profile</button>
    <button class="nav-link" id="v-pills-settings-tab" data-bs-toggle="pill" data-bs-target="#v-pills-settings" type="button" role="tab" aria-controls="v-pills-settings" aria-selected="false">Applied to programs</button>
    <button class="nav-link" id="v-pills-examples-tab" data-bs-toggle="pill" data-bs-target="#v-pills-examples" type="button" role="tab" aria-controls="v-pills-examples" aria-selected="false">Testing</button>
  </div>
  <%# tab content %>
  <div class="tab-content" id="v-pills-tabContent">
    <div class="tab-pane fade show active" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab">
      <h3>Hello <%= current_user.first_name %>!</h3>
    </div>
    <div class="tab-pane fade" id="v-pills-profile" role="tabpanel" aria-labelledby="v-pills-profile-tab">
      <% if @programs.empty? %>
        <div class="container">
          <div class="row">
            <div class="col-lg border card">
              You haven't saved any programs yet, explore them <%= link_to 'Browse Programs Now', programs_path   %>
            </div>
          </div>
        </div>
      </div>
    <% else %>
      <h3>The <%= @programs.size %> programs that you've previously saved.  Apply to them now!</h3>
      <div class="container">
        <div class="row">
          <div class="col-lg-5 border">
            <% @programs.each do |program| %>
              <%= render partial: 'programs/program_card_index', locals: {program: program} %>
            <% end %>
          </div>
          <div id="index_saved_programs", class="col-lg card border p-2 ms-2">
            <h3>Select one of the programs that you're previously saved on the left and its information will load here for you</h3>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="tab-pane fade" id="v-pills-messages" role="tabpanel" aria-labelledby="v-pills-messages-tab">
    <h3>Would you like to edit your user profile?  Click here: </h3>
    <%= link_to "Edit your user profile", edit_user_registration_path %>
    <h4>This is your current information</h4>
    <p>Name: <%= current_user.first_name %> <%= current_user.last_name %></p>
    <p>Location: <%= current_user.location %></p>
    <p>Bio: <%= current_user.bio %></p>
    <p>Age: <%= current_user.age %></p>
    <p>Goal: <%= current_user.goal %></p>
    <p>Interests: <%= current_user.interests %></p>
  </div>
  <div class="tab-pane fade" id="v-pills-settings" role="tabpanel" aria-labelledby="v-pills-settings-tab">
    <%# @applications.each do |application| %>
      <%#= render partial: 'applications/application_user_dashboard_card', locals: {application: application} %>
      <%# end %>
      <div class="container">
        <div class="row">
          <div class="col">
            <table class="table table-striped table-bordered table-hover caption-top">
              <caption>The programs that you've applied to and their current status</caption>
              <thead>
                <tr>
                  <th>Program</th>
                  <th>Company</th>
                  <th>Status</th>
                  <th>Submitted on</th>
                  <th>Updated on</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                <% @applications.each do |application| %>
                  <tr>
                    <td><%= application.program.title %></td>
                    <td> <%= application.program.user.organization_name %> </td>
                    <td><%= application.status.capitalize %></td>
                    <td><%= application.created_at.strftime("%m/%d/%y at %l:%M %p") %></td>
                    <td><%= application.updated_at.strftime("%m/%d/%y at %l:%M %p") %></td>
                    <td><%= link_to "See", program_application_path(application.program_id, application), data: { turbo: :true }, method: :get, class: 'badge bg-primary' %>
                      <%= link_to "Edit", edit_program_application_path(application.program_id, application), data: {turbo: :true }, method: :get, class: "badge bg-success" %>
                      <%= link_to "Delete", program_application_path(application.program_id, application), data: { turbo: :true, confirm: "Are you sure?" }, method: :delete, class: 'badge bg-danger', remote: true %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
    <div class="tab-pane fade" id="v-pills-examples" role="tabpanel" aria-labelledby="v-pills-examples-tab">
      <h3>Two column experiment</h3>
      <div class="container">
        <div class="row">
          <div class="col-12 col-lg">
            <% @programs.each do |program| %>
              <%= render partial: 'programs/program_card_index', locals: {program: program} %>
            <% end %>
          </div>
          <div class="col-12 col-lg border">
            <% @programs.each do |program| %>
              <%= render partial: 'programs/program_card_index', locals: {program: program} %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>